import Patience from '../assets/patience.webp';
import Purpose from '../assets/purpose.jpg';
import Presence from '../assets/presence.jpg';
import Leading from '../assets/Leading.webp';
import Winning from '../assets/leader.jpg';
import Blessed from '../assets/Marriage.webp';

const CardDataArticles = [
  {
    id: 1,
    title: 'PATIENCE: A VIRTUE FOR SUSTAINING CHRISTIAN COURTSHIP',
    description: 'Learn the importance of patience in Christian courtship and how it can help build a stronger relationship.',
    excerpt: 'Learn the importance of patience in Christian courtship and how it can help build a stronger relationship with God and your partner.',
    image: Patience,
    date: 'Feb 18, 2025',
    category: 'Courtship',
    author: 'Olusola Oladeni',
    views: 1250,
    readTime: 5,
    featured: true,
    link: '/patience',
    content: 'Patience is a virtue that is essential in any relationship, especially in Christian courtship...',
  },
  {
    id: 2,
    title: 'THE PRESENCE THAT MAKES THE DIFFERENCE IN A CHRISTIAN MARRIAGE',
    description: 'Discover how the presence of God can transform your marriage and bring you closer together.',
    excerpt: 'Discover how the presence of God can transform your marriage and bring you closer together in ways you never imagined.',
    image: Presence,
    date: 'Feb 18, 2025',
    category: 'Marriage',
    author: 'Olusola Oladeni',
    views: 980,
    readTime: 7,
    featured: true,
    link: '/presence',
    content: 'The presence of God is the foundation of a successful Christian marriage...',
  },
  {
    id: 3,
    title: 'PURPOSES OF HIS DIVINE POWER',
    description: 'Understanding the divine power available to believers and how to tap into it.',
    excerpt: 'Understanding the divine power available to believers and how to tap into it for daily living and spiritual growth.',
    image: Purpose,
    date: 'Feb 18, 2025',
    category: 'Purpose',
    author: 'Olusola Oladeni',
    views: 856,
    readTime: 6,
    featured: false,
    link: '/purpose',
    content: 'God has endowed believers with divine power to fulfill their purpose...',
  },
  {
    id: 4,
    title: 'LEADING THE CHURCH FOR ABIDING RESULTS',
    description: 'Essential principles for church leaders who want to achieve lasting impact.',
    excerpt: 'Essential principles for church leaders who want to achieve lasting impact in their ministry and congregation.',
    image: Leading,
    date: 'Feb 18, 2025',
    category: 'Leadership',
    author: 'Olusola Oladeni',
    views: 720,
    readTime: 8,
    featured: false,
    link: '/leader',
    content: 'Effective church leadership requires dedication, vision, and the fear of God...',
  },
  {
    id: 5,
    title: 'WINNING STRATEGIES FOR CHRISTIAN LIVING',
    description: 'Learn how to live a victorious Christian life in a challenging world.',
    excerpt: 'Learn how to live a victorious Christian life in a challenging world with practical strategies and biblical wisdom.',
    image: Winning,
    date: 'Feb 18, 2025',
    category: 'Christian Living',
    author: 'Olusola Oladeni',
    views: 1100,
    readTime: 6,
    featured: false,
    link: '/winning',
    content: 'As Christians, we are called to live victorious lives...',
  },
  {
    id: 6,
    title: 'BLESSED MARRIAGE: A GUIDE TO GODLY MARRIAGE',
    description: 'Discover the secrets to a blessed and fulfilling marriage from a biblical perspective.',
    excerpt: 'Discover the secrets to a blessed and fulfilling marriage from a biblical perspective and build a strong relationship.',
    image: Blessed,
    date: 'Feb 18, 2025',
    category: 'Marriage',
    author: 'Olusola Oladeni',
    views: 1450,
    readTime: 9,
    featured: false,
    link: '/blessed',
    content: 'A blessed marriage is one that is centered on God...',
  },
];

export default CardDataArticles;
